Practices header and footer
rash2x/ditate.me pull request #4
Opened 2021-06-23 09:00 UTC by RamazanIttiev

2021-06-23 09:12 UTC, rash2x commented on src/App/components/Footer/Footer.jsx
> +const Footer = () => {
Call file NavigationBar

2021-06-23 09:12 UTC, rash2x commented on src/App/components/Footer/Footer.jsx
> +    <BottomNavigation
make it fixed at the bottom

2021-06-23 09:12 UTC, rash2x commented on src/App/components/Footer/Footer.jsx
> +      <BottomNavigationAction component={Link} to="/" icon={<RecentActorsIcon />} />
Let's add titles for them Минибудды and Практики

2021-06-23 09:12 UTC, rash2x commented on src/App/components/Footer/Footer.jsx
> +      value={value}
use useRouter for setting current route and for changing route

2021-06-24 15:57 UTC, rash2x requested changes

2021-06-24 15:57 UTC, rash2x commented on src/assets/temp/arrow.svg
> +<svg width="80" height="82" viewBox="0 0 80 82" fill="none" xmlns="http://www.w3.org/2000/svg">
you don't need this

2021-06-24 15:57 UTC, rash2x commented on src/App/components/Practices/PracticeCard.jsx
> +const StyledCard = styled(Card)`
we use Base name for base of whole component. So, you have to call this card as Base

2021-06-24 15:57 UTC, rash2x commented on src/App/components/Practices/PracticeCard.jsx
> +  max-width: 335px;
Check all possible mobile viewports and make max-width according to them
https://www.icwebdesign.co.uk/common-viewport-sizes

because on my phone it looks as below 
![image](https://user-images.githubusercontent.com/3594973/123290564-0f731b80-d51a-11eb-8682-c7799cd90174.png)

2021-06-24 15:57 UTC, rash2x commented on src/App/components/Practices/PracticeCard.jsx
> +      <CardActionArea>
Set component={Link} to CardActionArea and make routes here. 
Please read this article https://material-ui.com/api/card-action-area/#component-name
And pay attention that CardActionArea extends ButtonBase props (which allows you to have "component" prop)

2021-06-24 15:57 UTC, rash2x commented on src/App/components/Practices/PracticeCard.jsx
> +          <Wrapper>
Instead of wrapping PracticeName and Image, you can wrap CardImage and place CardImage, PracticeName, and Avatar on the same level.

2021-06-24 15:57 UTC, rash2x commented on src/App/components/Practices/PracticeCard.jsx
> +const StyledCardContent = styled(CardContent)`
Try to short names, use just Content

2021-06-24 15:57 UTC, rash2x commented on src/App/components/Practices/PracticeCard.jsx
> +const CardImage = styled(CardMedia)`
Use semantic names, Thumbnail

2021-06-24 15:57 UTC, rash2x commented on src/App/components/Practices/PracticeCard.jsx
> +const Image = styled.img`
The name Image doesn't give you understand of what is that image. Use semantic names. For example Avatar or ProfileAvatar

2021-06-24 15:57 UTC, rash2x commented on src/App/components/Practices/PracticeCard.jsx
> +          <Typography variant="subtitle2" component="h2">
Try to make content simplier.

You have Content, inside you have Title and Info. Inside of Info are Date and Price. If you want to add Icon to Date or Price, just add Icon and stylize it with parent. as result you should have only 6 components. Try it!

2021-06-24 15:57 UTC, rash2x commented on src/App/components/NavigationBar/NavigationBar.jsx
> +    <StyledFooter
You can use Base name here.

2021-06-24 15:57 UTC, rash2x commented on src/App/pages/Practices/Practices.jsx
> +      <Link style={{ textDecoration: 'none' }} to="practiceID">
Place Link inside of PracticeCard to make it incapsulated. 
Try to understand that component should have everything necessary inside of itself. 
And props such as to/href/location should be passed by props. 
https://ru.reactjs.org/docs/web-components.html

2021-06-24 16:06 UTC, rash2x requested changes

2021-06-24 16:06 UTC, rash2x commented on src/App/components/Header/PracticesToolbar.jsx
> +      <BottomNavigation
You don't need to have BottomNavigation here. Use just div. What the logic? please describe why you place it here.

2021-06-24 16:06 UTC, rash2x commented on src/App/components/Header/PracticesToolbar.jsx
> +const Button = styled(BottomNavigationAction)`
You should use just IconButton for that. Please check https://material-ui.com/components/buttons/#icon-buttons

2021-06-24 16:06 UTC, rash2x commented on src/App/components/Header/PracticesToolbar.jsx
> +const StyledTitle = styled(Typography).attrs({
Just Title.

2021-06-24 16:06 UTC, rash2x commented on src/App/components/Header/PracticesToolbar.jsx
> +import MapIcon from '@material-ui/icons/Map';
instead of that, you can import icons like this
import {Map, ViewAgenda} from '@material-ui/icons';

2021-06-24 16:06 UTC, rash2x commented on src/App/components/Header/PracticesToolbar.jsx
> +  const [value, setValue] = React.useState(0);
No necessary for this code now.

2021-06-24 16:06 UTC, rash2x commented on src/App/components/NavigationBar/NavigationBar.jsx
> +  const [value, setValue] = React.useState(0);
As I commented before, use useRouter and set state according to route state

2021-06-24 16:06 UTC, rash2x commented on src/App/components/NavigationBar/NavigationBar.jsx
> +      onChange={(event, newValue) => {
move handlers from return function. use handleChange above to describe logic.

2021-06-25 07:22 UTC, RamazanIttiev commented on src/App/components/Practices/PracticeCard.jsx
> +          <Wrapper>
<Wrapper>
          <CardImage image={Teacher} title="Contemplative Reptile" />
          <PracticeName />
          <Avatar src={TeacherIcon} />
</Wrapper>

Like this? How can I place  <PracticeName /> and <Avatar /> right on the picture without position: absolute?

2021-06-25 07:34 UTC, RamazanIttiev commented on src/App/components/Header/PracticesToolbar.jsx
> +      <BottomNavigation
Because it has the same behaviour as bottom nav, and styling is also the same. It also shows active button. But can be as div and button as well

2021-06-25 09:02 UTC, rash2x commented on src/App/components/Header/PracticesToolbar.jsx
> +      <BottomNavigation
Disagree. BottomNavigation has specific behaviour and should be used only as bottom navigation

2021-06-25 09:14 UTC, RamazanIttiev commented on src/App/components/NavigationBar/NavigationBar.jsx
> +  const [value, setValue] = React.useState(0);
```suggestion
  
  const router = useRouter();
  let activeLink = router.pathname === '/practices' ? 1 : 0;
  const [value, setValue] = React.useState(activeLink);

  const handleChange = () => {
    if (router.pathname === '/practices') {
      setValue(prev => prev - 1);
    } else {
      setValue(prev => prev + 1);
    }
  };
```
Can it be done this way?

2021-06-28 19:57 UTC, rash2x commented on src/App/components/Calendar/Calendar.jsx
> +    <MuiPickersUtilsProvider utils={DateFnsUtils}>
move it to index.js, the providers should be placed there. (sometimes developers create another file calling Providers, but our project is still small for that)

2021-06-28 19:57 UTC, rash2x commented on src/App/components/Calendar/Calendar.jsx
> +      <Grid container justify="space-around">
Shouldn't be here. This is a layout element that should be out of the functional component.

2021-06-28 19:57 UTC, rash2x commented on src/App/components/FilterForm/FilterForm.jsx
> +  .MuiOutlinedInput-notchedOutline,
I'm suggesting moving these styles into theme.js. 

```
override: {
  MuiTextField: {
      root: {
          .MuiOutlinedInput-notchedOutline,
          .MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline,
          .Mui-focused,
          .MuiOutlinedInput-root:hover .MuiOutlinedInput-notchedOutline {
              border-color: ${props => props.theme.palette.background.paper};
          }
          
          ....
      }
  }
}
```

2021-06-28 19:57 UTC, rash2x commented on src/App/components/FilterForm/FilterForm.jsx
> +const Wrapper = styled.div`
You can call it as Actions / Footer

2021-06-28 19:57 UTC, rash2x commented on src/App/components/Header/PracticesToolbar.jsx
> +  font-size: 18px;
use rem for fonts

2021-06-28 19:57 UTC, rash2x commented on src/App/components/Header/PracticesToolbar.jsx
> +    <StyledToolbar>
Base

2021-06-28 19:57 UTC, rash2x commented on src/App/components/Header/PracticesToolbar.jsx
> +      <div>
call it as ViewButtons for example.

2021-06-28 19:57 UTC, rash2x commented on src/App/components/NavigationBar/NavigationBar.jsx
> +    <Base showLabels value={value} onChange={handleChange}>
move showLabels to .attrs({})

2021-06-28 19:57 UTC, rash2x commented on src/App/components/NavigationBar/NavigationBar.jsx
> +  border-radius: 28px;
All these styles except background and positioning are not necessary. remove them. Fab is already has theme all

2021-06-28 19:57 UTC, rash2x commented on src/App/components/NavigationBar/NavigationBar.jsx
> +        <div>
What this div is doing?

2021-06-28 19:57 UTC, rash2x commented on src/App/components/PracticeCard.jsx
> +          <Thumbnail image={Teacher} title="Contemplative Reptile" />
Clean the title

2021-06-28 19:57 UTC, rash2x commented on src/App/components/PracticeName.jsx
> +const PracticeName = () => {
PracticeBadge

2021-06-28 19:57 UTC, rash2x commented on src/App/components/PracticeName.jsx
> +    <Base variant="h2" component="h2">
move props to .attrs({})

2021-06-28 19:57 UTC, rash2x commented on src/App/pages/Practices/PracticeDetails.jsx
> +    <div>
Base

2021-06-28 19:57 UTC, rash2x commented on src/App/pages/Practices/PracticeDetails.jsx
> +      <BackgroundDiv>
Thumbnail

2021-06-28 19:57 UTC, rash2x commented on src/App/pages/Practices/PracticeDetails.jsx
> +    router.history.goBack();
use push. if you open the link in a new tab, by clicking the button you will be moved to the chrome home screen.

2021-06-28 19:57 UTC, rash2x commented on src/App/pages/Practices/PracticeDetails.jsx
> +          <Subtitle variant="subtitle2" component="h2">
move props to attrs

2021-06-28 19:57 UTC, rash2x commented on src/App/pages/Practices/PracticeDetails.jsx
> +          <Date variant="subtitle2" component="span">
move props to attrs

2021-06-28 19:57 UTC, rash2x commented on src/App/pages/Practices/PracticeDetails.jsx
> +          <Price variant="subtitle2" component="span">
move props to attrs

2021-06-28 19:57 UTC, rash2x commented on src/App/pages/Practices/PracticeDetails.jsx
> +      <Container>
the container should have top padding according to mockups

2021-06-28 19:57 UTC, rash2x commented on src/App/pages/Practices/PracticeDetails.jsx
> +          <Subtitle variant="subtitle2" component="h2">
subtitle1, component h1

2021-06-28 19:57 UTC, rash2x commented on src/App/pages/Practices/PracticeDetails.jsx
> +            Даосские практики с Константином Сухановым
body1

2021-06-28 19:57 UTC, rash2x commented on src/App/pages/Practices/PracticeDetails.jsx
> +          <Subtitle variant="subtitle2" component="h2">
and call this component as Title

2021-06-28 19:57 UTC, rash2x commented on src/App/pages/Practices/PracticeDetails.jsx
> +        <div>
TitleWrapper or something like this.

2021-06-28 19:57 UTC, rash2x commented on src/App/pages/Practices/PracticeDetails.jsx
> +        <Contact />
Extract hand image and add prop hands here

2021-06-28 20:50 UTC, RamazanIttiev commented on src/App/components/FilterForm/FilterForm.jsx
> +  .MuiOutlinedInput-notchedOutline,
I did not find right way to do it ( problems with Mui-focused and hover)

2021-06-28 20:53 UTC, RamazanIttiev commented on src/App/components/Header/PracticesToolbar.jsx
> +  font-size: 18px;
what about such things  font-size: ${props => props.theme.typography.fontSize}px; ?

2021-06-29 07:26 UTC, RamazanIttiev commented on src/App/components/Header/PracticesToolbar.jsx
> +      <div>
that div? even if it doesnt have any styling?

2021-06-29 07:36 UTC, RamazanIttiev commented on src/App/pages/Practices/PracticeDetails.jsx
> +    router.history.goBack();
if I use push('/') it goes to the top of the page, even if I clicked on user at the bottom

2021-06-29 07:42 UTC, RamazanIttiev commented on src/App/pages/Practices/PracticeDetails.jsx
> +      <Container>
But there is no need for that, or I can make my own div

2021-06-29 19:24 UTC, rash2x commented on src/App/pages/Practices/PracticeDetails.jsx
> +      <Container>
Please check mockups

2021-06-29 19:25 UTC, rash2x commented on src/App/components/Header/PracticesToolbar.jsx
> +  font-size: 18px;
we will adjust current font sizes according to mockups, but later.

2021-07-05 21:23 UTC, merged