Date and Events
rash2x/ditate.me pull request #6
Opened 2021-07-06 21:30 UTC by RamazanIttiev

2021-07-07 12:29 UTC, rash2x requested changes

2021-07-07 12:29 UTC, rash2x commented on src/App/pages/Practices/Practices.jsx
> +              new Date(event.startDate).getTime() > new Date().getTime() && (
move this condition out of UI (return code), like const isActualEvent

2021-07-07 12:29 UTC, rash2x commented on src/App/pages/Profile/Profile.jsx
> +  useEffect(() => {
Not necessary, I added required fields to airtable table. Please just add fields to the mapper and use it from currentTeacher.

2021-07-07 12:29 UTC, rash2x commented on src/App/pages/Profile/Profile.jsx
> +          {new Date(events.startDate).getTime() > new Date().getTime() && (
You have this condition twice, you can move it to helper

2021-07-07 12:29 UTC, rash2x commented on src/App/pages/Profile/Profile.jsx
> +      {currentTeacher.events && <CommingEvents>Ближайшие практики</CommingEvents> && (
Move ProfileEvents to component Events

2021-07-07 12:29 UTC, rash2x commented on src/App/pages/Profile/Profile.jsx
>        <StyledContact
If you have events, the Contact should be displayed

2021-07-07 12:29 UTC, rash2x commented on src/App/pages/Profile/Profile.jsx
>  import HoldingHands from '../../../assets/hands/holding-hands.svg';
I don't see it here, but at the top, you have a Button component which is imported differently from other material UI components, please fix it to resolve the css problem

2021-07-07 12:29 UTC, rash2x commented on src/App/components/PracticeCard.jsx
> +  const router = useRouter();
why do you need router?

2021-07-07 12:29 UTC, rash2x commented on src/App/components/PracticeCard.jsx
> +        <PracticeDate component="span">{new Date(startDate).toLocaleString()}</PracticeDate>
Let's add dayjs npm library and apply it for all dates.

2021-07-07 12:29 UTC, rash2x commented on src/App/airtable/mappers.jsx
> +    startDate: item.fields.StartDate,
There is also endDate, let's combine them to show the duration

2021-07-07 12:29 UTC, rash2x commented on src/App/components/PracticeCard.jsx
> -      <PracticeBadge name={practiceName} />
for PracticeBadge add also Practice color (I added it to airtable table, just add to mapper). And fix background-color and color in PracticeBadge component.

2021-07-07 19:41 UTC, RamazanIttiev commented on src/App/pages/Practices/Practices.jsx
> +              new Date(event.startDate).getTime() > new Date().getTime() && (
```suggestion
             const [state] = useContext(AirtableContext);
  const isActualEvents = state.events.map(
    event =>
      new Date(event.startDate).getTime() > new Date().getTime() && (
        <PracticeCard key={event.id} {...event} />
      ),
  );
  return (
    <>
      <HomeToolbar />
      <Base>{state.events ? isActualEvents : <></>}</Base>

      <NavigationBar />
    </>
  );
```
Like this?

2021-07-07 19:49 UTC, RamazanIttiev commented on src/App/components/PracticeCard.jsx
> +  const router = useRouter();
To check where the user is, cause u have different UI for Profile and Practices

2021-07-07 21:46 UTC, rash2x commented on src/App/components/PracticeCard.jsx
> +  const router = useRouter();
use prop like hideProfile={true} for that

2021-07-07 21:47 UTC, rash2x commented on src/App/components/PracticeCard.jsx
> -      <PracticeBadge name={practiceName} />
Solved in main

2021-07-07 21:47 UTC, rash2x commented on src/App/components/PracticeCard.jsx
> +        <PracticeDate component="span">{new Date(startDate).toLocaleString()}</PracticeDate>
there is date-fns, i prefer dayjs, let's remove the first one and add the second one

2021-07-07 21:51 UTC, rash2x commented on src/App/pages/Practices/Practices.jsx
> +              new Date(event.startDate).getTime() > new Date().getTime() && (
No. I meant only condition `new Date(event.startDate).getTime() > new Date().getTime()`

2021-07-07 21:52 UTC, rash2x commented on src/App/pages/Practices/Practices.jsx
> +              new Date(event.startDate).getTime() > new Date().getTime() && (
I would actually use const [actualEvents] = useState(state.events.filter(YOUR CONDITION));
This will help you when we will help filters or sort.

2021-07-08 14:03 UTC, RamazanIttiev commented on src/App/pages/Profile/Profile.jsx
> +          {new Date(events.startDate).getTime() > new Date().getTime() && (
```suggestion
          {new Date(events.startDate).getTime() > new Date().getTime() && (
           <>
          <CommingEvents>Ближайшие практики</CommingEvents>
          <EventsList>
            <PracticeCard hideMainInfo key={currentTeacher.id} {...currentTeacher} />
          </EventsList>
        </>
```

It is not that big and I will have to get current teacher twice, I think we should leave it like that

2021-07-13 20:18 UTC, merged